### ISSUE TITLE
The sample requires the `thumbnails` container to be available

### ISSUE THREAD

**Issue by docs-product** [Azure-Samples/azure-sdk-for-js-storage-blob-stream-nodejs#5]
Without the `thumbnails` container available in the storage account, the sample will error out. The container needs to be created ahead of time, and this needs to be documented in the `README.md`.

Alternatively, the container should be created at runtime.

**Comment by jongio** [comment]
This should be resolved.  Please reopen if you are able to reproduce.  Thanks
